// Add an include for each primitive
#include "primitives/primitive.h"
#include "primitives/plane-primitive.h"
#include "primitives/sphere-primitive.h"
#include "primitives/union-primitive.h"
#include "primitives/decorator-primitive.h"
#include "primitives/transformer-primitive.h"
#include "primitives/triangle-primitive.h"
#include "bounding-box-accelerator.h"
#include "mesh/mesh-renderer.h"
#include "primitives/mesh-primitive.h"